steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/travel-engine-2026/travel-engine/frontend:$COMMIT_SHA
      - -t
      - us-central1-docker.pkg.dev/travel-engine-2026/travel-engine/frontend:latest
      - ./frontend
    dir: 'travel-engine'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - us-central1-docker.pkg.dev/travel-engine-2026/travel-engine/frontend:$COMMIT_SHA

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - us-central1-docker.pkg.dev/travel-engine-2026/travel-engine/frontend:latest

images:
  - us-central1-docker.pkg.dev/travel-engine-2026/travel-engine/frontend:$COMMIT_SHA
  - us-central1-docker.pkg.dev/travel-engine-2026/travel-engine/frontend:latest
