version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images
      - ./tridev_database.db:/app/tridev_database.db
    env_file:
      - .env
    restart: always
