steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --tag=us-central1-docker.pkg.dev/$PROJECT_ID/travel-engine/frontend:latest
      - --build-arg=NEXT_PUBLIC_GOOGLE_CLIENT_ID=941368691857-76lb5rvam68e8551bo5ahu63hfr87f2s.apps.googleusercontent.com
      - --build-arg=NEXT_PUBLIC_API_URL=https://travel-engine-backend-710339309363.us-central1.run.app/api
      - --build-arg=NEXT_PUBLIC_FIREBASE_PROJECT_ID=travel-engine-2026
      - --build-arg=NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=travel-engine-2026.firebaseapp.com
      - --build-arg=NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=710339309363
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args: [push, 'us-central1-docker.pkg.dev/$PROJECT_ID/travel-engine/frontend:latest']
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/travel-engine/frontend:latest'
